eureka:
  instance:
    hostname: ${cf.instance.ip}
    nonSecurePort: ${cf.instance.port}
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${instance.guid}:${spring.application.name}:${server.port:8080}
  client:
    serviceUrl:
      defaultZone: http://eureka.192.168.11.11.xip.io/eureka/

spring:
  application:
    index: ${instance.index}

server:
  port: 8080

---

spring:
  profiles: aws

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.104.154.81.247.xip.io/eureka/
